LabMVC/LabMVC/Models/MathData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LabMVC.Models
{
    public class MathData
    {
        public float Value1 { get; set; }
        public float Value2 { get; set; }
        public float Sum { get; set; }
        public float Differnce { get; set; }
        public float Product { get; set; }
        public float Quotient { get; set; }
        public MathData
            (float Value1
            , float Value2
            , float Sum
            , float Differnce
            , float Product
            , float Quotient)
        {
            this.Value1 = Value1;
            this.Value2 = Value2;
            this.Sum = Sum;
            this.Differnce = Differnce;
            this.Product = Product;
            this.Quotient = Quotient;
        }
    }
}

LabMVC/LabMVC/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LabMVC.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
    }
}

LabMVC/LabMVC/Controllers/Lab03Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LabMVC.Controllers
{
    public class Lab03Controller : Controller
    {
        // GET: Lab03
        public ActionResult Index()
        {
            return View();
        }
    }
}

LabMVC/LabMVC/Controllers/Lab04Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LabMVC.Controllers
{
    public class Lab04Controller : Controller
    {
        // GET: Lab04
        public ActionResult Index()
        {
            return View();
        }
    }
}

LabMVC/LabMVC/Controllers/Lab05Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LabMVC.Controllers
{
    public class Lab05Controller : Controller
    {
        // GET: Lab05
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CalculateSum(string Value1, string Value2)
        {
            ViewData["Value1"] = Value1;
            ViewData["Value2"] = Value2;
            float fltSum = float.Parse(Value1) + float.Parse(Value2);
            ViewData["ResultingSum"] = fltSum.ToString();
            return View();
        }
    }
}

LabMVC/LabMVC/Controllers/Lab06Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LabMVC.Controllers
{
    public class Lab06Controller : Controller
    {
        // GET: Lab06
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CalculateValues(string Value1, string Value2)
        {
            float fltV1 = float.Parse(Value1);
            float fltV2 = float.Parse(Value2);
            float fltSum = fltV1 + fltV2;
            float fltDif = Math.Abs(fltV1 - fltV2);
            float fltPro = fltV1 * fltV2;
            float fltQuo = fltV1 / fltV2;
            LabMVC.Models.MathData objMD;
            objMD = new Models.MathData(fltV1, fltV2, fltSum, fltDif, fltPro, fltQuo);
            InsertData(fltV1, fltV2, fltSum, fltDif, fltPro, fltQuo);
            return View(objMD);
        }

        public void InsertData(float V1, float V2, float Sum, float Dif, float Pro, float Quo)
        {
            string strPath = Server.MapPath(@"~\App_Data\MathDB.mdf");
            string strCon = @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=""" + strPath + @"""; Integrated Security = True";
            //strCon = @"Data Source=(LocalDB)\MSSQLLocalDB; AttachDbFilename = E:\UW\CSHP230\LabMVC\LabMVC\App_Data\MathDB.mdf; Integrated Security = True";
            string strCmd = @"Exec pInsMathData " +
                            " @Value1 = " + V1.ToString() +
                            ",@Value2 = " + V2.ToString() +
                            ",@Sum = " + Sum.ToString() +
                            ",@Differnce = " + Dif.ToString() +
                            ",@Product = " + Pro.ToString() +
                            ",@Quotient = " + Quo.ToString();
            System.Data.SqlClient.SqlConnection objCon;
            System.Data.SqlClient.SqlCommand objCmd;
            objCon = new System.Data.SqlClient.SqlConnection(strCon);
            objCmd = new System.Data.SqlClient.SqlCommand(strCmd, objCon);
            objCon.Open();
            objCmd.ExecuteNonQuery();
            objCon.Close();
        }
    }
}

LabMVC/LabMVC/Views/Default/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        Hello World
    </div>
</body>
</html>

LabMVC/LabMVC/Views/Lab03/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <table border="1">
            <tr>
                <td>Requested URL</td>
                <td>Relative Path</td>
                <td>Full Path</td>
                <td>HTTP Request Type</td>
            </tr>
            <tr>
                @* Razor exsposes a Request Object with useful properties and methods! *@
                <td>@Request.Url</td>
                <td>@Request.FilePath</td>
                <td>@Request.MapPath(Request.FilePath)</td>
                <td>@Request.RequestType</td>
            </tr>
        </table>
    </div>

    @Html.ActionLink("Go to Lab 04", "Index", "Lab04")
</body>
</html>

LabMVC/LabMVC/Views/Lab04/Index.cshtml
@{Layout = null;}
@{ var Sum = 0f; var N1 = 0F; var N2 = 0f;
    if (IsPost)
    {
        // Collect the data from the Input textboxes on the page
        N1 = Request["text1"].AsFloat();
        N2 = Request["text2"].AsFloat();
        Sum = N1 + N2;
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Lab04</title>
</head>
<body>
    <p>Enter two numbers and then click the <strong>'Add Values'</strong> button.</p>
    <form action="" method="post">
        @*Use *@
        <p>@Html.Label("text1", "First Number: ")@Html.TextBox("text1")</p>
        <p>@Html.Label("text1", "Second Number: ")@Html.TextBox("text2")</p>
        <p><input type="submit" value="Add Values" /></p>
    </form>
    <p>The Sum of @N1 and @N2 is @Sum</p>

    @Html.ActionLink("Go to Lab 03", "Index", "Lab03")
</body>
</html>

LabMVC/LabMVC/Views/Lab05/CalculateSum.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CalculateSum</title>
</head>
<body>
    <h2>CalculateSum</h2>
    <div>
        The Sum of @ViewData["Value1"] and @ViewData["Value2"] is: @ViewData["ResultingSum"]
    </div>
</body>
</html>

LabMVC/LabMVC/Views/Lab05/Index.cshtml
@{Layout = null;}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        @using (@Html.BeginForm("CalculateSum", "Lab05", FormMethod.Post))
        { //start the form
            <p><span>Enter the First Value: </span> @Html.TextBox("Value1", 0) </p>
            <p><span>Enter the Second Value: </span> @Html.TextBox("Value2", 0)</p>
            <p><input type="submit" id="ProcessSum" value="Process Sum" /></p>
        } @*End the form*@
    </div>
</body>
</html>

LabMVC/LabMVC/Views/Lab06/CalculateValues.cshtml
@model LabMVC.Models.MathData
@{
    var v1 = Model.Value1;
    var v2 = Model.Value2;
    var s = Model.Sum;
    var d = Model.Differnce;
    var p = Model.Product;
    var q = Model.Quotient;
}

@{ Layout = null;}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CalculateValues</title>
</head>
<body>
    <h2>Calculate Values</h2>
    <div>
        @*You can get data using a Razor variable or an HTML helper*@
        Given the values of @v1 and @Html.DisplayFor(model => model.Value2)
        <p>You get the following results:</p>
        <ul>
            <li>Sum: @s</li>
            <li>Difference: @d</li>
            <li>Product: @p</li>
            <li>Quotient: @q</li>
        </ul>
    </div>
</body>
</html>

LabMVC/LabMVC/Views/Lab06/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        @using (@Html.BeginForm("CalculateValues", "Lab06", FormMethod.Post))
        { //start the form
            <p><span>Enter the First Value: </span> @Html.TextBox("Value1", 0) </p>
            <p><span>Enter the Second Value: </span> @Html.TextBox("Value2", 0)</p>
            <p><input type="submit" id="ProcessValues" value="Process Values" /></p>
        } @*End the form*@
    </div>
</body>
</html>